### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by roesel** [glacials/whatsinstandard#136]
Hi, 
I love your site, it's a simple, quick and effective resource for what it does. However, the new design (or rather layout?) goes exactly against this: 
1) The list of editions now takes up the whole screen without providing any new information compared to the old design, while also being significantly less understandable. 
2) The sorting is not clear immediately, since the design changed from one column to two rows (at least in its current state) and the fancy moving progress bars only add to the confusion.
3) The useful info (bans etc) which was immediately visible before is now hidden below the line and requires scrolling. 

The main problem is that I do not know for sure which sets are leaving standard "in 4 months", which "in a year" and which have "18 months to exit" even after staring at the site for several minutes - [link to image](https://puu.sh/DTV5h/7ef4df0a8e.png). I am not against change in general, but this redesign was a downgrade in experience (in my personal opinion).

Thank you for your work and best of luck with the site in the future.

**Comment by NilsEnevoldsen** [comment]
FWIW, I agree with all three points. This design feels too heavy for what it represents. I’d even return to the layout without the banned card image(s).

**Comment by glacials** [comment]
Thanks for the detailed feedback! I will work to address these issues when I have a free moment, either with simplifications or reverting to the old design.

To give perspective, I felt the old design was too visually busy and had been working on something more simple slowly over a couple of months. 18 hours before M20 was about to enter, I realized the site broke completely when we didn't know the name of the next set, which had never happened before in the history of the site, and was about to happen with M20's release.

Because of that I sort of rushed this design out rather than patching the old one. It looks like that was the wrong move! Sorry for any confusion I caused.

**Comment by glacials** [comment]
I've just pushed an update which attempts to address these issues as well as some shared on Twitter. Summary:

1. The page no longer pushes the bans and *What* is *Standard?* sections below the fold.
2. Somewhat moved back to columns, but each group of sets that drop together is its own column.

For perspective vs the old and previous designs: (same exact screenshot region)

Old:
<img width="1620" alt="Screen Shot 2019-07-18 at 15 40 22" src="https://user-images.githubusercontent.com/438911/61496867-6ce7b080-a972-11e9-8808-6e422ab33655.png">

Previous:
<img width="1620" alt="Screen Shot 2019-07-18 at 15 42 48" src="https://user-images.githubusercontent.com/438911/61496955-bdf7a480-a972-11e9-8e9d-7c5a238fb648.png">

Now:
<img width="1620" alt="Screen Shot 2019-07-18 at 15 40 42" src="https://user-images.githubusercontent.com/438911/61496868-6eb17400-a972-11e9-8588-959f08503456.png">

Let me know what you think about the changes. I am always open to further criticism.

**Comment by NilsEnevoldsen** [comment]
"Now" is certainly an improvement over "Previous", but even with an open mind I still do believe "Old" is better. The progress bars feel unnecessary. Here is an (unsolicited) suggestion, with vertical and horizontal options, that attempts to capture some of the redesign ideas while preserving some simplicity. 

<img width="1218" alt="Screen Shot 2019-07-19 at 1 10 27 PM" src="https://user-images.githubusercontent.com/222743/61553089-99113900-aa27-11e9-8b96-a9c771725f6e.png">

<img width="1112" alt="Screen Shot 2019-07-19 at 1 30 25 PM" src="https://user-images.githubusercontent.com/222743/61553854-649e7c80-aa29-11e9-9a2a-9122850231fd.png">

**Comment by roesel** [comment]
I tend to agree exactly with @NilsEnevoldsen on this one. "Now" is most definitely better than "previous", but I still don't see the progress bars adding anything, especially clarity. So for me, "old" was the best.

But no matter what the end result will be, I appreciate the revert back to "previous", thank you!

**Comment by glacials** [comment]
Ok, thanks for the input all! And fantastic visual suggestions @NilsEnevoldsen! 🎉 When I get a free moment I'll have a detailed look & think. Based on feedback, progress bars did not communicate what I thought they would, so they definitely need to go.

**Comment by DominusMaximus** [comment]
I don't know how much the redesign has changed since this thread started, but overall the most important info is right up top, which I like. I was going to request that each set's 3 character code be shown, but then learned hovering over set graphic brings it up, which was a nice touch. I would just suggest considering whether most people will find that mouseover with the valuable info. Maybe if many things moused over with extra info, and you noted this at beginning of page.

But yeah good stuff.

**Comment by glacials** [comment]
Here are the changes, inspired by all y'alls suggestions and @NilsEnevoldsen's screenshots:

- Killed progress bars
- Killed ambiguous "24 months" etc. labels
- Simplified colors
- Moved & simplified the button that toggles the last round of exits
- Switched mostly from relative dates to absolute dates
- Enlarged the mouseover region that shows the set code

Old:
<img width="1599" alt="Screen Shot 2019-07-29 at 11 48 19" src="https://user-images.githubusercontent.com/438911/62074133-f317b880-b1f6-11e9-8dbb-6d5839147965.png">

New:
<img width="1600" alt="Screen Shot 2019-07-29 at 11 48 39" src="https://user-images.githubusercontent.com/438911/62074153-f90d9980-b1f6-11e9-95db-40085f5992b3.png">

One thing the initial redesign was trying to solve was the misinterpretation in #91. The hacky fix I implemented at the time worked, but made the page visually complicated.

By going back mostly to our old layout, this issue comes up again. For now I'm trying to solve it by using small "until `date`" text instead of "Leaving Standard in `time`" text, hoping it feels like a footnote instead of a section title. And the horizontal layout helps fight the notion that it could be a feed.

All of us here have too many preconceptions and context to know what a good design for a new player is. This problem isn't one that we personally will ever experience. We are users and what we think matters, but there is another class of users who by definition aren't involved enough to voice their opinions. We should keep them in mind as well.

**Comment by glacials** [comment]
Closing due to no further feedback, feel free to open with more.
